### ISSUE TITLE
NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by abtru32** [avierstr/amplicon_sorter#23]
I keep trying to run the amplicon sorter on my Mac, but I keep getting this error message. I'm extremely new to bioinformatics, so any help would be greatly appreciated!
This is the error I keep getting:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/abbytruman/Downloads/amplicon_sorter.py", line 763, in similarity
    similarg = args.similar_genes/100
               ^^^^
NameError: name 'args' is not defined
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Process Process-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/abbytruman/Downloads/amplicon_sorter.py", line 763, in similarity
    similarg = args.similar_genes/100
               ^^^^

**Comment by avierstr** [comment]
The problem is the Mac M1 processor.  See:
[https://github.com/avierstr/amplicon_sorter/issues/14](url)

**Comment by avierstr** [comment]
I have now added an single core version that should work:
[amplicon_sorter_single.py](https://github.com/avierstr/amplicon_sorter/blob/master/amplicon_sorter_single.py)
